/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Junit;

import org.junit.Test;
import static org.junit.Assert.*;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        System.out.println("");
    }
    Library lib=new Library();
    @Test public void test() 
    {
    	assertEquals(20,lib.add(lib.a, lib.b) );
    }
  
}
