/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Junit;


public class Library {
	static int a=10;
	static int b=10;
	int add(int a,int b) {
		return a+b;
	}
	public static void main(String[] args) {
       
        Library library=new Library();
        library.add(a,b);
    	
    }
}

